# sudo: required
dist: trusty
language: scala
scala: 2.11.7

branches:
  only:
    - master

#before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq graphviz smlnj jedit xvfb
script:
 - bash scripts/travis/deploy_doc.sh
 - cd src
 - sbt compile
 - sbt deployFull
 - sbt test
 # - git clone http://gl.mathhub.info/meta/inf.git
 # - inf/config/MMT/testScripts/testUrtheories.sh
 # - inf/config/MMT/testScripts/testExamples.sh
 # - inf/config/MMT/testScripts/testSms.sh
 # - inf/config/MMT/testScripts/testTeX.sh
 # - cp inf/config/MMT/cf95c94bae142eeed300a254d964f0bf $HOME/.subversion/auth/svn.ssl.server/
 # - inf/config/MMT/setupTwelf.sh > /dev/null
 # - export PATH=/usr/local/share/twelf-mod/bin:$PATH
 # - inf/config/MMT/testScripts/testLATIN.sh
 # - inf/config/MMT/testScripts/testJEdit.sh

env:
  global:
  - ENCRYPTION_LABEL: "25a07036478c"
  - COMMIT_AUTHOR_EMAIL: "tkw01536@gmail.com"
