name: CI

on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel
  
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  ci:
    # Skip CI if the commit message of the head commit of a push
    # contains "skip ci" or "ci skip"
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenJDK 14 and sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.14

      - name: Install Dependencies
        run: |
          cd src
          sbt ++2.13.4 update

      - name: Build 'mmt.jar'
        run: |
          cd src
          sbt ++2.13.4 deploy

      - name: Store 'mmt.jar' artifact
        uses: actions/upload-artifact@v2
        with:
          name: mmt.jar
          path: ./deploy/mmt.jar

      - name: Unit Tests
        run: |
          cd src
          sbt ++2.13.4 test

      - name: Integration Tests
        shell: bash
        run: |
          export TEST_USE_BRANCH=${GITHUB_REF#refs/heads/}
          java -cp deploy/mmt.jar info.kwarc.mmt.test.TestRunner
