name: CI

on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel
  
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  ci:
    # Skip CI if the commit message of the head commit of a push
    # contains "skip ci" or "ci skip"
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      #- name: Create Nigthly Prerelease
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ github.ref }}
      #    release_name: Nightly Prerelease (${{ github.ref }})
      #    body: will be overwritten later anyway
      #    draft: true
      #    prerelease: true
      #- name: cancelling
      #  uses: andymckay/cancel-action@0.2
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenJDK 14 and sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.14

      - name: Install Dependencies
        run: |
          cd src
          sbt ++2.12.9 update

      - name: Build 'mmt.jar'
        run: |
          cd src
          sbt ++2.12.9 deploy

      - name: Store 'mmt.jar' artifact
        uses: actions/upload-artifact@v2
        with:
          name: mmt.jar
          path: ./deploy/mmt.jar
          
      #- name: "Nightly release: set 'nightly' tag to current commit"
      #  # https://github.community/t/nightly-builds-latest-branch-releases/725/5
      #  run: |
      #    git config --local user.name "UniFormal/MMT GitHub Action"
      #    git config --local user.email "action@mmt.uniformal.github.com"
      #    git tag -f nightly
      #- name: "Nightly release: force-push new 'nightly' tag" DANGEROUS, FORCE PUSHING
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ github.ref }}
      #    force: true
      #    tags: true
      #- name: "Nightly release: delete old 'nightly' release assets" DANGEROUS, has access to all releases
      #  uses: mknejp/delete-release-assets@v1
      #  with:
      #    token: ${{ github.token }}
      #    tag: nightly
      #    assets: '*'
      #- name: "Nightly release: upload new 'mmt.jar'"
      #  uses: meeDamian/github-release@2.0
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    tag: nightly
      #    files: mmt-${{ GITHUB_SHA }}.jar:./deploy/mmt.jar
      #    name: Nightly Prerelease 
      #    body: |
      #      This is a nightly prerelease of the `mmt.jar` automatically built, uploaded, and updated by
      #      GitHub actions from the latest commit on the `devel` branch.
      #      Please see <https://github.com/UniFormal/MMT/actions> for more information.
      #      
      #      In particular, this nightly build does not need to pass integration or unit tests for it to be
      #      uploaded. Use with caution.
      #    prerelease: true
      #    allow_override: true
      #
      - name: Unit Tests
        run: |
          cd src
          sbt ++2.12.9 test

      - name: Integration Tests
        shell: bash
        run: |
          export TEST_USE_BRANCH=${GITHUB_REF#refs/heads/}
          java -cp deploy/mmt.jar info.kwarc.mmt.test.TestRunner
