name: CI

on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel
  
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  ci:
    # Skip CI if the commit message of the head commit of a push
    # contains "skip ci" or "ci skip"
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Create Nigthly Prerelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Nightly Prerelease (${{ github.ref }})
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: true
      - name: cancelling
        uses: andymckay/cancel-action@0.2
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenJDK 14 and sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.14

      - name: Install Dependencies
        run: |
          cd src
          sbt ++2.12.9 update

      - name: Build 'mmt.jar'
        run: |
          cd src
          sbt ++2.12.9 deploy
      
      - name: Get version (Git commit/ref/tag)
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      #- name: Store 'mmt.jar' artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: mmt.jar
      #    path: ./deploy/mmt.jar
          
      - name: Create/update Nightly Release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_name: Nightly Prerelease 
          body: |
            This is a nightly prerelease of the `mmt.jar` automatically built, uploaded, and updated by
            GitHub actions from the latest commit on the `devel` branch.
            Please see <https://github.com/UniFormal/MMT/actions> for more information.
            
            In particular, this nightly build does not need to pass integration or unit tests for it to be
            uploaded. Use with caution.
          prerelease: true
          
      - name: Upload 'mmt.jar' to Nightly Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.update_release.outputs.upload_url }}
          asset_path: ./deploy/mmt.jar
          asset_name: mmt_${{ steps.get_version.outputs.VERSION }}$.jar
          asset_content_type: application/java-archive

      - name: Unit Tests
        run: |
          cd src
          sbt ++2.12.9 test

      - name: Integration Tests
        shell: bash
        run: |
          export TEST_USE_BRANCH=${GITHUB_REF#refs/heads/}
          java -cp deploy/mmt.jar info.kwarc.mmt.test.TestRunner
